name: Build Desktop – Windows · macOS · Linux

on:
  push:
    tags: ["v*.*.*"] # e.g. v0.1.0

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: tauri-apps/tauri-action@v0.2.0
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          working-directory: apps/desktop
      - name: Build NSIS installer
        if: runner.os == 'Windows'
        run: |
          choco install nsis -y
          cd apps/desktop/packaging/windows
          makensis libreca.nsi
      - name: Sign installer
        if: runner.os == 'Windows' && env.CERT_THUMBPRINT != ''
        run: |
          pwsh apps/desktop/packaging/windows/sign-installer.ps1 -ExePath Libreca-*.exe
        env:
          CERT_THUMBPRINT: ${{ secrets.CERT_THUMBPRINT }}
      - uses: actions/upload-artifact@v4
        with:
          name: Libreca-Windows
          path: apps/desktop/packaging/windows/Libreca-*.exe
